SET NOCOUNT ON
BEGIN TRANSACTION

declare
	@CURR_SUBJ_ID	int,
	@TERR_ID	int,
	@KODTERR	varchar(11)

select @CURR_SUBJ_ID = SUBJ.SUBJ_ID, @TERR_ID = SUBJ.TERR_ID, @KODTERR = KTERR.KODTERR from SUBJ JOIN KTERR ON SUBJ.TERR_ID = KTERR.TERR_ID where SUBJ_ID in (select SUBJ_ID FROM CURR_SUBJ)

insert into KFS (
	KOD
	)
select KFS_
from #ORG
where KFS_ <> '00'
and KFS_ not in (select KOD from KFS)
and KFS_ IS NOT NULL
group by KFS_
if @@ERROR != 0
begin
	goto end_err
end

insert into KOPF (
	KOD
	)
select KOPF_
from #ORG
where KOPF_ <> '00'
and KOPF_ not in (select KOD from KOPF)
and KOPF_ IS NOT NULL
group by KOPF_
if @@ERROR != 0
begin
	goto end_err
end

insert into ORG (
	PARENT,
	FS_ID,
	INN,
	OKPO,
	OKONH,
	SOOGU,
	KOPF_ID,
	KODREG,
	REGDATE,
	REGNUM,
	ORGNAME,
	ORGSNAME,
	COMMENT,
	FIZADDR,
	URADDR,
	POSTADDR,
	PHONE,
	FAX,
	EMAIL,
	WWW,
	MYORG,
	CONFDATE,
	MAINOKONH,
	KONH_ID,
	OKBV,
	OCCUPATION,
	FIRST_DATE,
	LAST_DATE,
	REG_PLACE,
	OUT_REASON,
	OUT_DATE,
	SBM_ID,
	TERR_ID,
	EXT_ID,
	HAS_BRON,
	CHECKED,
	F6_SHIFR
	)
select
	O.V_NAME,
	KFS.FS_ID,
	O.INN,
	O.OKPO,
	O.OKONHS_,
	O.SOOGU_,
	KOPF.KOPF_ID,
	@KODTERR,
	O.DR,
	O.NR,
	LEFT(O.[NAME], 250),
	LEFT(O.[NAME], 50),
	O.COMMENTS,
	O.F_ADR,
	O.ADR,
	O.P_ADR,
	O.TFON,
	NULL,
	NULL,
	NULL,
	0,
	CONVERT(datetime, CONVERT(char(10), GETDATE(), 104), 104),
	O.OKONH_,
	KONH.KONH_ID,
	O.BUH,
	O.VD,
	O.D_FIRST,
	O.D_LAST,
	O.R_ADR,
	O.[OUT],
	O.D_OUT,
	VV5.ID,
	@TERR_ID,
	O.ORGID,
	O.FL_BR,
	O.FL_RAB,
	NULL
from #ORG O 
	LEFT JOIN KFS ON O.KFS_ = KFS.KOD 
	LEFT JOIN KOPF ON O.KOPF_ = KOPF.KOPF_ID
	LEFT JOIN KONH ON O.KODONH = KONH.KONH_KOD
	LEFT JOIN VV5 ON O.SV_D = VV5.KOD
where SOATO_ = @KODTERR
and OKPO_ IS NOT NULL
if @@ERROR != 0
begin
	goto end_err
end

insert into ORG_CONT (
	ORGID,
	DEPART,
	POST,
	FIO,
	PHONE,
	FAX,
	EMAIL,
	IS_GEN,
	IS_VUS
	)
select
	OO.ORGID,
	NULL,
	NULL,
	O.DIREC,
	O.TFON,
	NULL,
	NULL,
	1,
	0
from #ORG O JOIN ORG OO ON OO.EXT_ID = O.ORGID AND OO.TERR_ID = @TERR_ID
where O.DIREC IS NOT NULL OR O.TFON IS NOT NULL
if @@ERROR != 0
begin
	goto end_err
end

insert into ORG_CONT (
	ORGID,
	DEPART,
	POST,
	FIO,
	PHONE,
	FAX,
	EMAIL,
	IS_GEN,
	IS_VUS
	)
select
	OO.ORGID,
	NULL,
	NULL,
	O.VUS_FIO,
	O.VUS_TEL,
	NULL,
	NULL,
	0,
	1
from #ORG O JOIN ORG OO ON OO.EXT_ID = O.ORGID AND OO.TERR_ID = @TERR_ID
where O.VUS_FIO IS NOT NULL OR O.VUS_TEL IS NOT NULL
if @@ERROR != 0
begin
	goto end_err
end

INSERT INTO OSN (
	ORGID,
	BASE_ID,
	DOC_ID,
	DOC_NO,
	DOC_DATE
	)
SELECT
	O.ORGID,
	VV3.ID,
	VV4.ID,
	OS.NUMB,
	OS.DD
FROM 	#OSN OS left join VV3 on OS. KOD1 = VV3.KOD left join VV4 on OS.KOD2 = VV4.KOD
	join #ORG on OS.OKPO = #ORG.OKPO_ join ORG O ON O.EXT_ID = #ORG.ORGID AND O.TERR_ID = @TERR_ID
if @@ERROR != 0
begin
	goto end_err
end

INSERT INTO PER (
	ORGID,
	DOC_ID,
	DOC_NO,
	START_DATE,
	END_DATE,
	PER_NO,
	RAZD_NO
	)
SELECT
	O.ORGID,
	VV4.ID,
	P.NUMB_D,
	P.DD_D,
	P.DD_END,
	P.NUMB_P,
	P.RAZD_P
FROM 	#PER P left join VV4 on P.KOD2 = VV4.KOD
	join #ORG on P.OKPO = #ORG.OKPO_ join ORG O ON O.EXT_ID = #ORG.ORGID AND O.TERR_ID = @TERR_ID
if @@ERROR != 0
begin
	goto end_err
end

INSERT INTO FORM6HDR (
	ORGID,
	ORGNAME,
	F6_SHIFR,
	ORG_SHIFR,
	F6_COUNT,
	KUO_COUNT,
	RAB_COUNT,
	ZAP_COUNT,
	ZAB_COUNT,
	CHECKED,
	CONFDATE,
	SUBJ_ID
	)
SELECT	DISTINCT
	O.ORGID,
	O.ORGNAME,
	O.F6_SHIFR,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	CONVERT(datetime, CONVERT(char(10), GETDATE(), 104), 104),
	NULL
FROM	#O_S_V S
	join #ORG OO on S.OKPO = OO.OKPO_ join ORG O on OO.ORGID = O.EXT_ID AND O.TERR_ID = @TERR_ID
if @@ERROR != 0
begin
	goto end_err
end

INSERT INTO FORM6 (
	CPROF_ID,
	F6_ID,
	PRINT_NAME,
	EXPRESSION,
	CALCULATE,
	COL_B
	)
SELECT
	C.CPROF_ID,
	F.F6_ID,
	C.PRINT_NAME,
	C.EXPRESSION,
	0,
	C.LINE_NO
FROM	KCPROF C cross join FORM6HDR F
	join ORG O on F.ORGID = O.ORGID join #ORG OO on O.EXT_ID = OO.ORGID AND O.TERR_ID = @TERR_ID
if @@ERROR != 0
begin
	goto end_err
end

update	#SPEC	SET
	CPROF_ID = CASE KOD
		WHEN '002' THEN 100
		WHEN '011' THEN 210
		WHEN '012' THEN 220
		WHEN '013' THEN 230
		WHEN '014' THEN 240
		WHEN '015' THEN 250
		WHEN '017' THEN 264
		WHEN '018' THEN 265
		WHEN '021' THEN 300
		WHEN '031' THEN 410
		WHEN '032' THEN 420
		WHEN '033' THEN 430
		WHEN '034' THEN 440
		WHEN '035' THEN 450
		WHEN '036' THEN 460
		WHEN '037' THEN 470
		WHEN '038' THEN 480
		WHEN '041' THEN 495
		WHEN '042' THEN 496
		WHEN '050' THEN 500
		WHEN '010' THEN 200
		WHEN '016' THEN 260
		WHEN '030' THEN 400
		WHEN '001' THEN 1000
	END
if @@ERROR != 0
begin
	goto end_err
end

update	FORM6	SET
	COL_1 = CASE WHEN V1 = 0 THEN NULL ELSE V1 END,
	COL_2 = CASE WHEN V2 = 0 THEN NULL ELSE V2 END,
	COL_3 = CASE WHEN V3 = 0 THEN NULL ELSE V3 END,
	COL_4 = CASE WHEN V4 = 0 THEN NULL ELSE V4 END,
	COL_5 = CASE WHEN V5 = 0 THEN NULL ELSE V5 END,
	COL_6 = CASE WHEN V6 = 0 THEN NULL ELSE V6 END,
	COL_7 = CASE WHEN B7 = 0 THEN NULL ELSE B7 END,
	COL_8 = CASE WHEN B8 = 0 THEN NULL ELSE B8 END,
	COL_9 = CASE WHEN B9 = 0 THEN NULL ELSE B9 END,
	COL_10 = CASE WHEN B10 = 0 THEN NULL ELSE B10 END,
	COL_11 = CASE WHEN B11 = 0 THEN NULL ELSE B11 END,
	COL_12 = CASE WHEN B12 = 0 THEN NULL ELSE B12 END,
	COL_13 = CASE WHEN B13 = 0 THEN NULL ELSE B13 END,
	COL_14 = CASE WHEN B14 = 0 THEN NULL ELSE B14 END,
	COL_15 = CASE WHEN B15 = 0 THEN NULL ELSE B15 END,
	COL_16 = CASE WHEN B16 = 0 THEN NULL ELSE B16 END
from	#O_S_V S join #SPEC ON S.KOD_SPEC = #SPEC.KOD
	join #ORG OO on S.OKPO = OO.OKPO_ join ORG O on OO.ORGID = O.EXT_ID AND O.TERR_ID = @TERR_ID
	join FORM6HDR F on F.ORGID = O.ORGID
where	FORM6.CPROF_ID = #SPEC.CPROF_ID
and	FORM6.F6_ID = F.F6_ID
if @@ERROR != 0
begin
	goto end_err
end

update	FORM6	SET
	COL_1 = F.COL_1,
	COL_2 = F.COL_2,
	COL_3 = F.COL_3,
	COL_4 = F.COL_4,
	COL_5 = F.COL_5,
	COL_6 = F.COL_6,
	COL_7 = F.COL_7,
	COL_8 = F.COL_8,
	COL_9 = F.COL_9,
	COL_10 = F.COL_10,
	COL_11 = F.COL_11,
	COL_12 = F.COL_12,
	COL_13 = F.COL_13,
	COL_14 = F.COL_14,
	COL_15 = F.COL_15,
	COL_16 = F.COL_16
from	(select F.* from FORM6 F join FORM6HDR FH on F.F6_ID = FH.F6_ID
	join ORG O on FH.ORGID = O.ORGID join #ORG OO on O.EXT_ID = OO.ORGID and O.TERR_ID = @TERR_ID
	where	F.CPROF_ID = 1000) F
	where FORM6.CPROF_ID = 2000
	and FORM6.F6_ID = F.F6_ID
if @@ERROR != 0
begin
	goto end_err
end

update	FORM6HDR	SET
	RAB_COUNT = COL_1,
	ZAP_COUNT = COL_2,
	ZAB_COUNT = COL_7
from	FORM6
WHERE	FORM6.F6_ID = FORM6HDR.F6_ID
AND	CPROF_ID = 2000
if @@ERROR != 0
begin
	goto end_err
end

update	ORG	SET
	EXT_ID = ORGID
where	TERR_ID = @TERR_ID
if @@ERROR != 0
begin
	goto end_err
end

COMMIT TRANSACTION
goto	end_script

end_err:
ROLLBACK TRANSACTION

end_script:
